import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client.js";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcrypt";

const connectionString =
  process.env.DATABASE_URL ??
  "postgresql://postgres:postgres@localhost:5432/kiroportal?schema=public";

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString }),
});

const BCRYPT_ROUNDS = 12;

async function seedUsers() {
  console.log("🌱 Seeding users...");

  const users = [
    {
      email: "admin@kiroportal.com",
      password: "Admin123!",
      name: "Admin User",
      role: "ADMIN" as const,
      company: "KiroPortal Inc.",
      phone: "+1-555-0100",
    },
    {
      email: "manager@kiroportal.com",
      password: "Manager123!",
      name: "Manager User",
      role: "MANAGER" as const,
      company: "KiroPortal Inc.",
      phone: "+1-555-0200",
    },
    {
      email: "client@kiroportal.com",
      password: "Client123!",
      name: "Client User",
      role: "CLIENT" as const,
      company: "Acme Corp.",
      phone: "+1-555-0300",
    },
  ];

  for (const user of users) {
    const hashedPassword = await bcrypt.hash(user.password, BCRYPT_ROUNDS);
    await prisma.user.upsert({
      where: { email: user.email },
      update: {
        name: user.name,
        password: hashedPassword,
        role: user.role,
        company: user.company,
        phone: user.phone,
      },
      create: {
        email: user.email,
        password: hashedPassword,
        name: user.name,
        role: user.role,
        company: user.company,
        phone: user.phone,
      },
    });
    console.log(`  ✓ User: ${user.email} (${user.role})`);
  }
}

async function seedProducts() {
  console.log("🌱 Seeding products...");

  const products = [
    {
      slug: "dell-poweredge-r750-xeon-gold-5318y",
      name: "Dell PowerEdge R750 - Xeon Gold 5318Y",
      sku: "SRV-DELL-R750-001",
      brand: "Dell",
      condition: "NEW" as const,
      price: 8499.99,
      stock: 12,
      stockStatus: "IN_STOCK" as const,
      cpuFamily: "Xeon Gold",
      cpuModel: "5318Y",
      cpuCores: 24,
      cpuThreads: 48,
      cpuFreqMhz: 2100,
      cpuBoostMhz: 3400,
      cpuSocket: "LGA 4189",
      cpuCount: 2,
      cpuMaxCount: 2,
      ramGb: 256,
      ramType: "DDR4 ECC",
      ramFreqMhz: 3200,
      ramSlotsUsed: 8,
      ramSlotsTotal: 32,
      diskType: "NVMe",
      diskGb: 3840,
      diskBays: 8,
      diskRaid: "RAID 5",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 2,
      psuWatt: 1400,
      weightKg: 18.5,
      description:
        "Enterprise-grade 2U rack server with dual Xeon Gold processors, ideal for virtualization and database workloads. Features hot-swap NVMe storage and redundant power supplies.",
      isActive: true,
      isFeatured: true,
      customFields: JSON.stringify({
        warranty: { label: "Warranty", type: "text", value: "3 Years ProSupport", showInFilter: false },
        management: { label: "Remote Management", type: "text", value: "iDRAC9 Enterprise", showInFilter: true },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/dell-r750-front.jpg", alt: "Dell PowerEdge R750 Front View", order: 0, isMain: true },
        { url: "https://placeholder.kiroportal.com/products/dell-r750-rear.jpg", alt: "Dell PowerEdge R750 Rear View", order: 1, isMain: false },
      ],
    },
    {
      slug: "hp-proliant-dl380-gen10-plus",
      name: "HP ProLiant DL380 Gen10 Plus - Xeon Gold 6330",
      sku: "SRV-HP-DL380-002",
      brand: "HP",
      condition: "NEW" as const,
      price: 7899.00,
      stock: 8,
      stockStatus: "IN_STOCK" as const,
      cpuFamily: "Xeon Gold",
      cpuModel: "6330",
      cpuCores: 28,
      cpuThreads: 56,
      cpuFreqMhz: 2000,
      cpuBoostMhz: 3100,
      cpuSocket: "LGA 4189",
      cpuCount: 2,
      cpuMaxCount: 2,
      ramGb: 512,
      ramType: "DDR4 ECC",
      ramFreqMhz: 3200,
      ramSlotsUsed: 16,
      ramSlotsTotal: 32,
      diskType: "SAS",
      diskGb: 7200,
      diskBays: 12,
      diskRaid: "RAID 6",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 2,
      psuWatt: 1600,
      weightKg: 22.0,
      description:
        "High-performance 2U rack server designed for demanding enterprise workloads. Dual Xeon Gold 6330 processors with 512GB RAM for memory-intensive applications.",
      isActive: true,
      isFeatured: true,
      customFields: JSON.stringify({
        warranty: { label: "Warranty", type: "text", value: "3 Years Care Pack", showInFilter: false },
        management: { label: "Remote Management", type: "text", value: "iLO 5 Advanced", showInFilter: true },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/hp-dl380-front.jpg", alt: "HP ProLiant DL380 Gen10 Plus Front View", order: 0, isMain: true },
        { url: "https://placeholder.kiroportal.com/products/hp-dl380-angle.jpg", alt: "HP ProLiant DL380 Gen10 Plus Angle View", order: 1, isMain: false },
      ],
    },
    {
      slug: "supermicro-sys-1029u-xeon-platinum-8380",
      name: "Supermicro SYS-1029U - Xeon Platinum 8380",
      sku: "SRV-SM-1029U-003",
      brand: "Supermicro",
      condition: "NEW" as const,
      price: 12999.99,
      stock: 3,
      stockStatus: "LOW_STOCK" as const,
      cpuFamily: "Xeon Platinum",
      cpuModel: "8380",
      cpuCores: 40,
      cpuThreads: 80,
      cpuFreqMhz: 2300,
      cpuBoostMhz: 3400,
      cpuSocket: "LGA 4189",
      cpuCount: 2,
      cpuMaxCount: 2,
      ramGb: 512,
      ramType: "DDR4 ECC",
      ramFreqMhz: 3200,
      ramSlotsUsed: 16,
      ramSlotsTotal: 32,
      diskType: "NVMe",
      diskGb: 7680,
      diskBays: 10,
      diskRaid: "RAID 10",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 1,
      psuWatt: 1000,
      weightKg: 14.2,
      description:
        "Ultra-dense 1U server with dual Xeon Platinum processors. Perfect for AI/ML inference workloads and high-performance computing clusters.",
      isActive: true,
      isFeatured: true,
      customFields: JSON.stringify({
        gpu: { label: "GPU Support", type: "boolean", value: true, showInFilter: true },
        cooling: { label: "Cooling", type: "text", value: "Redundant fans with optimal airflow", showInFilter: false },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/sm-1029u-front.jpg", alt: "Supermicro SYS-1029U Front View", order: 0, isMain: true },
      ],
    },
    {
      slug: "dell-poweredge-t640-xeon-e-2388g",
      name: "Dell PowerEdge T640 - Xeon E-2388G",
      sku: "SRV-DELL-T640-004",
      brand: "Dell",
      condition: "NEW" as const,
      price: 3299.99,
      stock: 20,
      stockStatus: "IN_STOCK" as const,
      cpuFamily: "Xeon E",
      cpuModel: "E-2388G",
      cpuCores: 8,
      cpuThreads: 16,
      cpuFreqMhz: 3200,
      cpuBoostMhz: 5100,
      cpuSocket: "LGA 1200",
      cpuCount: 1,
      cpuMaxCount: 1,
      ramGb: 64,
      ramType: "DDR4 ECC",
      ramFreqMhz: 3200,
      ramSlotsUsed: 2,
      ramSlotsTotal: 4,
      diskType: "SSD",
      diskGb: 1920,
      diskBays: 8,
      diskRaid: "RAID 1",
      diskHotswap: true,
      formFactor: "Tower",
      unitCount: null,
      psuWatt: 750,
      weightKg: 28.5,
      description:
        "Versatile tower server ideal for small businesses and remote offices. Quiet operation with enterprise-grade reliability.",
      isActive: true,
      isFeatured: false,
      customFields: JSON.stringify({
        noiseLevel: { label: "Noise Level", type: "text", value: "< 30 dB at idle", showInFilter: false },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/dell-t640-front.jpg", alt: "Dell PowerEdge T640 Front View", order: 0, isMain: true },
        { url: "https://placeholder.kiroportal.com/products/dell-t640-side.jpg", alt: "Dell PowerEdge T640 Side View", order: 1, isMain: false },
      ],
    },
    {
      slug: "lenovo-thinksystem-sr650-v2-used",
      name: "Lenovo ThinkSystem SR650 V2 - Xeon Gold 5317 (Used)",
      sku: "SRV-LEN-SR650-005",
      brand: "Lenovo",
      condition: "USED" as const,
      price: 4199.00,
      priceOld: 6899.00,
      stock: 5,
      stockStatus: "IN_STOCK" as const,
      cpuFamily: "Xeon Gold",
      cpuModel: "5317",
      cpuCores: 12,
      cpuThreads: 24,
      cpuFreqMhz: 3000,
      cpuBoostMhz: 3600,
      cpuSocket: "LGA 4189",
      cpuCount: 2,
      cpuMaxCount: 2,
      ramGb: 128,
      ramType: "DDR4 ECC",
      ramFreqMhz: 2933,
      ramSlotsUsed: 8,
      ramSlotsTotal: 32,
      diskType: "SSD",
      diskGb: 3840,
      diskBays: 8,
      diskRaid: "RAID 5",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 2,
      psuWatt: 1100,
      weightKg: 19.8,
      description:
        "Pre-owned Lenovo ThinkSystem SR650 V2 in excellent condition. Fully tested and certified with 90-day warranty. Great value for mid-range workloads.",
      isActive: true,
      isFeatured: false,
      customFields: JSON.stringify({
        usageHours: { label: "Usage Hours", type: "number", value: 12500, showInFilter: false },
        certifiedDate: { label: "Certification Date", type: "text", value: "2024-11-15", showInFilter: false },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/lenovo-sr650-front.jpg", alt: "Lenovo ThinkSystem SR650 V2 Front View", order: 0, isMain: true },
      ],
    },
    {
      slug: "hp-proliant-dl360-gen10-refurbished",
      name: "HP ProLiant DL360 Gen10 - Xeon Gold 6248R (Refurbished)",
      sku: "SRV-HP-DL360-006",
      brand: "HP",
      condition: "REFURBISHED" as const,
      price: 3599.00,
      priceOld: 5999.00,
      stock: 7,
      stockStatus: "IN_STOCK" as const,
      cpuFamily: "Xeon Gold",
      cpuModel: "6248R",
      cpuCores: 24,
      cpuThreads: 48,
      cpuFreqMhz: 3000,
      cpuBoostMhz: 4000,
      cpuSocket: "LGA 3647",
      cpuCount: 1,
      cpuMaxCount: 2,
      ramGb: 128,
      ramType: "DDR4 ECC",
      ramFreqMhz: 2933,
      ramSlotsUsed: 4,
      ramSlotsTotal: 24,
      diskType: "SSD",
      diskGb: 1920,
      diskBays: 4,
      diskRaid: "RAID 1",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 1,
      psuWatt: 800,
      weightKg: 12.5,
      description:
        "Factory-refurbished HP ProLiant DL360 Gen10 with full manufacturer warranty. Compact 1U form factor ideal for dense rack deployments.",
      isActive: true,
      isFeatured: false,
      customFields: JSON.stringify({
        refurbGrade: { label: "Refurbishment Grade", type: "text", value: "Grade A", showInFilter: true },
        warranty: { label: "Warranty", type: "text", value: "1 Year HP Certified", showInFilter: false },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/hp-dl360-front.jpg", alt: "HP ProLiant DL360 Gen10 Front View", order: 0, isMain: true },
        { url: "https://placeholder.kiroportal.com/products/hp-dl360-rear.jpg", alt: "HP ProLiant DL360 Gen10 Rear View", order: 1, isMain: false },
      ],
    },
    {
      slug: "supermicro-4u-storage-epyc-7543",
      name: "Supermicro 4U Storage Server - AMD EPYC 7543",
      sku: "SRV-SM-4U-007",
      brand: "Supermicro",
      condition: "NEW" as const,
      price: 9799.00,
      stock: 4,
      stockStatus: "LOW_STOCK" as const,
      cpuFamily: "EPYC",
      cpuModel: "7543",
      cpuCores: 32,
      cpuThreads: 64,
      cpuFreqMhz: 2800,
      cpuBoostMhz: 3700,
      cpuSocket: "SP3",
      cpuCount: 1,
      cpuMaxCount: 2,
      ramGb: 256,
      ramType: "DDR4 ECC",
      ramFreqMhz: 3200,
      ramSlotsUsed: 8,
      ramSlotsTotal: 16,
      diskType: "HDD",
      diskGb: 96000,
      diskBays: 24,
      diskRaid: "RAID 6",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 4,
      psuWatt: 2000,
      weightKg: 38.0,
      description:
        "High-capacity 4U storage server with 24 hot-swap bays. AMD EPYC processor delivers excellent price-to-performance for file storage and backup workloads.",
      isActive: true,
      isFeatured: true,
      customFields: JSON.stringify({
        maxRawStorage: { label: "Max Raw Storage", type: "text", value: "576 TB (24x 24TB)", showInFilter: false },
        networkPorts: { label: "Network Ports", type: "text", value: "2x 25GbE + 2x 1GbE", showInFilter: true },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/sm-4u-storage-front.jpg", alt: "Supermicro 4U Storage Server Front View", order: 0, isMain: true },
        { url: "https://placeholder.kiroportal.com/products/sm-4u-storage-open.jpg", alt: "Supermicro 4U Storage Server Open View", order: 1, isMain: false },
      ],
    },
    {
      slug: "dell-poweredge-r650-epyc-7413-used",
      name: "Dell PowerEdge R650 - AMD EPYC 7413 (Used)",
      sku: "SRV-DELL-R650-008",
      brand: "Dell",
      condition: "USED" as const,
      price: 3899.00,
      priceOld: 6499.00,
      stock: 2,
      stockStatus: "LOW_STOCK" as const,
      cpuFamily: "EPYC",
      cpuModel: "7413",
      cpuCores: 24,
      cpuThreads: 48,
      cpuFreqMhz: 2650,
      cpuBoostMhz: 3600,
      cpuSocket: "SP3",
      cpuCount: 1,
      cpuMaxCount: 2,
      ramGb: 128,
      ramType: "DDR4 ECC",
      ramFreqMhz: 3200,
      ramSlotsUsed: 4,
      ramSlotsTotal: 16,
      diskType: "NVMe",
      diskGb: 3840,
      diskBays: 10,
      diskRaid: "RAID 5",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 1,
      psuWatt: 800,
      weightKg: 14.0,
      description:
        "Pre-owned Dell PowerEdge R650 with AMD EPYC processor. Excellent for web hosting and general-purpose workloads. Tested and certified.",
      isActive: true,
      isFeatured: false,
      customFields: JSON.stringify({
        usageHours: { label: "Usage Hours", type: "number", value: 8200, showInFilter: false },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/dell-r650-front.jpg", alt: "Dell PowerEdge R650 Front View", order: 0, isMain: true },
      ],
    },
    {
      slug: "lenovo-thinksystem-st650-v2-tower",
      name: "Lenovo ThinkSystem ST650 V2 Tower - Xeon Gold 5315Y",
      sku: "SRV-LEN-ST650-009",
      brand: "Lenovo",
      condition: "NEW" as const,
      price: 4599.00,
      stock: 15,
      stockStatus: "IN_STOCK" as const,
      cpuFamily: "Xeon Gold",
      cpuModel: "5315Y",
      cpuCores: 8,
      cpuThreads: 16,
      cpuFreqMhz: 3200,
      cpuBoostMhz: 3600,
      cpuSocket: "LGA 4189",
      cpuCount: 1,
      cpuMaxCount: 2,
      ramGb: 64,
      ramType: "DDR4 ECC",
      ramFreqMhz: 2933,
      ramSlotsUsed: 2,
      ramSlotsTotal: 16,
      diskType: "SSD",
      diskGb: 960,
      diskBays: 8,
      diskRaid: "RAID 1",
      diskHotswap: true,
      formFactor: "Tower",
      unitCount: null,
      psuWatt: 750,
      weightKg: 32.0,
      description:
        "Powerful tower server for small-to-medium businesses. Quiet operation, expandable design, and enterprise-grade reliability without the need for a server rack.",
      isActive: true,
      isFeatured: false,
      customFields: JSON.stringify({
        noiseLevel: { label: "Noise Level", type: "text", value: "< 35 dB at idle", showInFilter: false },
        expansionSlots: { label: "PCIe Slots", type: "number", value: 7, showInFilter: true },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/lenovo-st650-front.jpg", alt: "Lenovo ThinkSystem ST650 V2 Front View", order: 0, isMain: true },
        { url: "https://placeholder.kiroportal.com/products/lenovo-st650-side.jpg", alt: "Lenovo ThinkSystem ST650 V2 Side View", order: 1, isMain: false },
      ],
    },
    {
      slug: "hp-proliant-dl380-gen10-refurbished-budget",
      name: "HP ProLiant DL380 Gen10 - Xeon E-2236 (Refurbished)",
      sku: "SRV-HP-DL380R-010",
      brand: "HP",
      condition: "REFURBISHED" as const,
      price: 1899.00,
      priceOld: 3499.00,
      stock: 0,
      stockStatus: "OUT_OF_STOCK" as const,
      cpuFamily: "Xeon E",
      cpuModel: "E-2236",
      cpuCores: 6,
      cpuThreads: 12,
      cpuFreqMhz: 3400,
      cpuBoostMhz: 4800,
      cpuSocket: "LGA 1151",
      cpuCount: 1,
      cpuMaxCount: 1,
      ramGb: 32,
      ramType: "DDR4 ECC",
      ramFreqMhz: 2666,
      ramSlotsUsed: 2,
      ramSlotsTotal: 6,
      diskType: "HDD",
      diskGb: 2000,
      diskBays: 4,
      diskRaid: "RAID 1",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 2,
      psuWatt: 500,
      weightKg: 16.0,
      description:
        "Budget-friendly refurbished server for entry-level workloads. Ideal for development environments, testing, and light production use.",
      isActive: true,
      isFeatured: false,
      customFields: JSON.stringify({
        refurbGrade: { label: "Refurbishment Grade", type: "text", value: "Grade B", showInFilter: true },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/hp-dl380-refurb-front.jpg", alt: "HP ProLiant DL380 Gen10 Refurbished Front View", order: 0, isMain: true },
      ],
    },
    {
      slug: "supermicro-sys-220gp-epyc-9354-preorder",
      name: "Supermicro SYS-220GP - AMD EPYC 9354 (Pre-Order)",
      sku: "SRV-SM-220GP-011",
      brand: "Supermicro",
      condition: "NEW" as const,
      price: 15999.99,
      stock: 0,
      stockStatus: "PRE_ORDER" as const,
      cpuFamily: "EPYC",
      cpuModel: "9354",
      cpuCores: 32,
      cpuThreads: 64,
      cpuFreqMhz: 3250,
      cpuBoostMhz: 3800,
      cpuSocket: "SP5",
      cpuCount: 2,
      cpuMaxCount: 2,
      ramGb: 512,
      ramType: "DDR5 ECC",
      ramFreqMhz: 4800,
      ramSlotsUsed: 8,
      ramSlotsTotal: 24,
      diskType: "NVMe",
      diskGb: 15360,
      diskBays: 8,
      diskRaid: "RAID 10",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 2,
      psuWatt: 2200,
      weightKg: 24.0,
      description:
        "Next-generation GPU-optimized server with AMD EPYC 9354 processors and DDR5 memory. Designed for AI/ML training workloads. Available for pre-order.",
      isActive: true,
      isFeatured: true,
      customFields: JSON.stringify({
        gpuSlots: { label: "GPU Slots", type: "number", value: 4, showInFilter: true },
        expectedShip: { label: "Expected Ship Date", type: "text", value: "Q2 2025", showInFilter: false },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/sm-220gp-front.jpg", alt: "Supermicro SYS-220GP Front View", order: 0, isMain: true },
        { url: "https://placeholder.kiroportal.com/products/sm-220gp-gpu.jpg", alt: "Supermicro SYS-220GP GPU Configuration", order: 1, isMain: false },
      ],
    },
    {
      slug: "dell-poweredge-r750xs-xeon-gold-5320-used",
      name: "Dell PowerEdge R750xs - Xeon Gold 5320 (Used)",
      sku: "SRV-DELL-R750XS-012",
      brand: "Dell",
      condition: "USED" as const,
      price: 5499.00,
      priceOld: 8999.00,
      stock: 3,
      stockStatus: "LOW_STOCK" as const,
      cpuFamily: "Xeon Gold",
      cpuModel: "5320",
      cpuCores: 26,
      cpuThreads: 52,
      cpuFreqMhz: 2200,
      cpuBoostMhz: 3400,
      cpuSocket: "LGA 4189",
      cpuCount: 2,
      cpuMaxCount: 2,
      ramGb: 256,
      ramType: "DDR4 ECC",
      ramFreqMhz: 2933,
      ramSlotsUsed: 8,
      ramSlotsTotal: 32,
      diskType: "SAS",
      diskGb: 4800,
      diskBays: 16,
      diskRaid: "RAID 6",
      diskHotswap: true,
      formFactor: "Rack",
      unitCount: 2,
      psuWatt: 1400,
      weightKg: 20.5,
      description:
        "Pre-owned Dell PowerEdge R750xs with dual Xeon Gold 5320 processors. Excellent for virtualization clusters and enterprise applications. Fully tested.",
      isActive: true,
      isFeatured: false,
      customFields: JSON.stringify({
        usageHours: { label: "Usage Hours", type: "number", value: 15800, showInFilter: false },
        previousUse: { label: "Previous Use", type: "text", value: "Data Center - Virtualization", showInFilter: false },
      }),
      images: [
        { url: "https://placeholder.kiroportal.com/products/dell-r750xs-front.jpg", alt: "Dell PowerEdge R750xs Front View", order: 0, isMain: true },
        { url: "https://placeholder.kiroportal.com/products/dell-r750xs-interior.jpg", alt: "Dell PowerEdge R750xs Interior", order: 1, isMain: false },
      ],
    },
  ];

  for (const product of products) {
    const { images, ...productData } = product;
    await prisma.product.upsert({
      where: { sku: productData.sku },
      update: {
        ...productData,
        price: productData.price,
        priceOld: productData.priceOld ?? null,
        weightKg: productData.weightKg ?? null,
        images: {
          deleteMany: {},
          create: images,
        },
      },
      create: {
        ...productData,
        price: productData.price,
        priceOld: productData.priceOld ?? null,
        weightKg: productData.weightKg ?? null,
        images: {
          create: images,
        },
      },
    });
    console.log(`  ✓ Product: ${productData.name} (${productData.condition})`);
  }
}

async function main() {
  console.log("🚀 Starting database seed...\n");

  await seedUsers();
  console.log("");
  await seedProducts();

  console.log("\n✅ Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
